	<meta property="og:type" content="article" />
	<meta property="og:title" content="<?php echo $wo['title']; ?>" />
	<meta property="og:description" content="<?php echo $wo['description']; ?>" />
	<meta property="og:url" content="<?php echo $wo['story']['url']; ?>" />
	<meta property="og:image" content="https://img.youtube.com/vi/<?php echo $wo['story']['postYoutube']; ?>/hqdefault.jpg" />
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="<?php echo $wo['title']; ?>" />
	<meta name="twitter:description" content="<?php echo $wo['description']; ?>" />
	<meta name="twitter:image" content="https://img.youtube.com/vi/<?php echo $wo['story']['postYoutube']; ?>/hqdefault.jpg" />
	<meta name="twitter:image:alt" content="<?php echo $wo['title']; ?> Image" />
