      <meta property="og:type" content="article" />
      <meta property="og:title" content="<?php echo $wo['title']; ?>" />
      <meta property="og:url" content="<?php echo $wo['story']['url']; ?>" />
<?php
//    Check if site url has trailing slash
if (preg_match("/\/$/", $wo['config']['site_url'])) { ?>
      <meta property="og:image" content="<?php echo $wo['config']['site_url'].$wo['story']['postFile']; ?>" />
<?php } else { ?>
      <meta property="og:image" content="<?php echo $wo['config']['site_url']."/".$wo['story']['postFile']; ?>" />
<?php } ?>
      <meta property="og:description" content="<?php echo $wo['description']; ?>" />
      <meta name="twitter:card" content="summary" />
      <meta name="twitter:title" content="<?php echo $wo['title']; ?>" />
      <meta name="twitter:description" content="<?php echo $wo['description']; ?>" />
<?php
//    Check if site url has trailing slash
if (preg_match("/\/$/", $wo['config']['site_url'])) { ?>
      <meta name="twitter:image" content="<?php echo $wo['config']['site_url'].$wo['story']['postFile']; ?>" />
<?php } else { ?>
      <meta name="twitter:image" content="<?php echo $wo['config']['site_url']."/".$wo['story']['postFile']; ?>" />
<?php } ?>
