	<meta property="og:type" content="website" />
	<meta property="og:title" content="<?php echo $wo['title']; ?>" />
	<meta property="og:description" content="<?php echo $wo['description']; ?>" />
	<meta property="og:url" content="<?php echo $wo['config']['site_url']; ?>" />
	<meta property="og:image" content="https://blastfmsocial.media/images/blastfmsocial-site-logo.jpg" />
	<meta property="og:image:secure_url" content="https://blastfmsocial.media/images/blastfmsocial-site-logo.jpg" />
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="<?php echo $wo['title']; ?>" />
	<meta name="twitter:description" content="<?php echo $wo['description']; ?>" />
	<meta name="twitter:image" content="https://blastfmsocial.media/images/blastfmsocial-site-logo.jpg" />
