	<meta property="og:type" content="article" />
	<meta property="og:url" content="<?php echo $wo['story']['url']; ?>" />
	<meta property="og:title" content="<?php echo $wo['title']; ?>" />
	<meta property="og:image" content="<?php echo imageUrl($wo['story']['postSticker']); ?>" />
	<meta property="og:description" content="<?php echo $wo['description']; ?>" /> 
	<meta name="twitter:card" content="summary" />   
	<meta name="twitter:title" content="<?php echo $wo['title']; ?>" />
	<meta name="twitter:description" content="<?php echo $wo['description']; ?>" />
	<meta name="twitter:image" content="<?php echo imageUrl($wo['story']['postSticker']); ?>" />
